// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents an access event.
public struct Access: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Associated email, such as "foo@google.com".
  ///
  /// The email address of the authenticated user or a service account acting on
  /// behalf of a third party principal making the request. For third party
  /// identity callers, the `principal_subject` field is populated instead of
  /// this field. For privacy reasons, the principal email address is sometimes
  /// redacted. For more information, see [Caller identities in audit
  /// logs](https://cloud.google.com/logging/docs/audit#user-id).
  public var principalEmail: Swift.String = Swift.String()

  /// Caller's IP address, such as "1.1.1.1".
  public var callerIp: Swift.String = Swift.String()

  /// The caller IP's geolocation, which identifies where the call came from.
  public var callerIpGeo: Geolocation? = nil

  /// Type of user agent associated with the finding. For example, an operating
  /// system shell or an embedded or standalone application.
  public var userAgentFamily: Swift.String = Swift.String()

  /// The caller's user agent string associated with the finding.
  public var userAgent: Swift.String = Swift.String()

  /// This is the API service that the service account made a call to, e.g.
  /// "iam.googleapis.com"
  public var serviceName: Swift.String = Swift.String()

  /// The method that the service account called, e.g. "SetIamPolicy".
  public var methodName: Swift.String = Swift.String()

  /// A string that represents the principal_subject that is associated with the
  /// identity. Unlike `principal_email`, `principal_subject` supports principals
  /// that aren't associated with email addresses, such as third party
  /// principals. For most identities, the format is
  /// `principal://iam.googleapis.com/{identity pool name}/subject/{subject}`.
  /// Some GKE identities, such as GKE_WORKLOAD, FREEFORM, and GKE_HUB_WORKLOAD,
  /// still use the legacy format `serviceAccount:{identity pool
  /// name}[{subject}]`.
  public var principalSubject: Swift.String = Swift.String()

  /// The name of the service account key that was used to create or exchange
  /// credentials when authenticating the service account that made the request.
  /// This is a scheme-less URI full resource name. For example:
  ///
  /// "//iam.googleapis.com/projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}/keys/{key}".
  ///
  public var serviceAccountKeyName: Swift.String = Swift.String()

  /// The identity delegation history of an authenticated service account that
  /// made the request. The `serviceAccountDelegationInfo[]` object contains
  /// information about the real authorities that try to access Google Cloud
  /// resources by delegating on a service account. When multiple authorities are
  /// present, they are guaranteed to be sorted based on the original ordering of
  /// the identity delegation events.
  public var serviceAccountDelegationInfo: [ServiceAccountDelegationInfo] = []

  /// A string that represents a username. The username provided depends on the
  /// type of the finding and is likely not an IAM principal. For example, this
  /// can be a system username if the finding is related to a virtual machine, or
  /// it can be an application login username.
  public var userName: Swift.String = Swift.String()

  /// Initialize a new instance of `Access`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Access().with { $0.principalEmail = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Access"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
