// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents details about an anomaly detected in an AI agent's behavior.
public struct AgentAnomaly: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The overall confidence score indicating the likelihood that this session
  /// contains a true anomaly. The score ranges from 0.0 to 1.0, where 1.0
  /// signifies 100% confidence in the presence of an anomaly and 0.0 signifies
  /// 0% confidence.
  public var confidenceScore: Swift.Double = Swift.Double()

  /// The list of references to specific detectors that identified anomalies
  /// within this session.
  public var detectorReferences: [DetectorReference] = []

  /// References to the OpenTelemetry invocations.
  public var invocationReferences: [InvocationReference] = []

  /// Initialize a new instance of `AgentAnomaly`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AgentAnomaly().with { $0.confidenceScore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.AgentAnomaly"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
