// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Information about DDoS attack volume and classification.
public struct Attack: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Total PPS (packets per second) volume of attack.
  public var volumePpsLong: Swift.Int64 = Swift.Int64()

  /// Total BPS (bytes per second) volume of attack.
  public var volumeBpsLong: Swift.Int64 = Swift.Int64()

  /// Type of attack, for example, 'SYN-flood', 'NTP-udp', or 'CHARGEN-udp'.
  public var classification: Swift.String = Swift.String()

  /// Total PPS (packets per second) volume of attack. Deprecated - refer to
  /// volume_pps_long instead.
  @available(*, deprecated)
  public var volumePps: Swift.Int32 = Swift.Int32()

  /// Total BPS (bytes per second) volume of attack. Deprecated - refer to
  /// volume_bps_long instead.
  @available(*, deprecated)
  public var volumeBps: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Attack`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Attack().with { $0.volumePpsLong = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let volumePpsLong = CodingKeys(stringValue: "volumePpsLong")
    static let volumeBpsLong = CodingKeys(stringValue: "volumeBpsLong")
    static let classification = CodingKeys(stringValue: "classification")
    static let volumePps = CodingKeys(stringValue: "volumePps")
    static let volumeBps = CodingKeys(stringValue: "volumeBps")

    static let _knownKeys: Set<Swift.String> = [
      "volumePpsLong",
      "volumeBpsLong",
      "classification",
      "volumePps",
      "volumeBps",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .volumePpsLong) {
      self.volumePpsLong = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .volumeBpsLong) {
      self.volumeBpsLong = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .classification) {
      self.classification = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .volumePps) {
      self.volumePps = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .volumeBps) {
      self.volumeBps = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.volumePpsLong, forKey: .volumePpsLong)
    try container.encode(self.volumeBpsLong, forKey: .volumeBpsLong)
    try container.encode(self.classification, forKey: .classification)
    try container.encode(self.volumePps, forKey: .volumePps)
    try container.encode(self.volumeBps, forKey: .volumeBps)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Attack"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
