// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// AWS metadata associated with the resource, only applicable if the finding's
/// cloud provider is Amazon Web Services.
public struct AwsMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The AWS organization associated with the resource.
  public var organization: AwsMetadata.AwsOrganization? = nil

  /// A list of AWS organizational units associated with the resource, ordered
  /// from lowest level (closest to the account) to highest level.
  public var organizationalUnits: [AwsMetadata.AwsOrganizationalUnit] = []

  /// The AWS account associated with the resource.
  public var account: AwsMetadata.AwsAccount? = nil

  /// Initialize a new instance of `AwsMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsMetadata().with { $0.organization = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An organization is a collection of accounts that are centrally managed
  /// together using consolidated billing, organized hierarchically with
  /// organizational units (OUs), and controlled with policies.
  public struct AwsOrganization: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The unique identifier (ID) for the organization. The regex pattern for an
    /// organization ID string requires "o-" followed by from 10 to 32 lowercase
    /// letters or digits.
    public var id: Swift.String = Swift.String()

    /// Initialize a new instance of `AwsOrganization`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AwsOrganization().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.AwsMetadata.AwsOrganization"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// An Organizational Unit (OU) is a container of AWS accounts within a root of
  /// an organization. Policies that are attached to an OU apply to all accounts
  /// contained in that OU and in any child OUs.
  public struct AwsOrganizationalUnit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The unique identifier (ID) associated with this OU. The regex pattern for
    /// an organizational unit ID string requires "ou-" followed by from 4 to 32
    /// lowercase letters or digits (the ID of the root that contains the OU).
    /// This string is followed by a second "-" dash and from 8 to 32 additional
    /// lowercase letters or digits. For example, "ou-ab12-cd34ef56".
    public var id: Swift.String = Swift.String()

    /// The friendly name of the OU.
    public var name: Swift.String = Swift.String()

    /// Initialize a new instance of `AwsOrganizationalUnit`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AwsOrganizationalUnit().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.AwsMetadata.AwsOrganizationalUnit"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// An AWS account that is a member of an organization.
  public struct AwsAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The unique identifier (ID) of the account, containing exactly 12 digits.
    public var id: Swift.String = Swift.String()

    /// The friendly name of this account.
    public var name: Swift.String = Swift.String()

    /// Initialize a new instance of `AwsAccount`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AwsAccount().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.AwsMetadata.AwsAccount"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.AwsMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
