// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Azure metadata associated with the resource, only applicable if the finding's
/// cloud provider is Microsoft Azure.
public struct AzureMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A list of Azure management groups associated with the resource, ordered
  /// from lowest level (closest to the subscription) to highest level.
  public var managementGroups: [AzureMetadata.AzureManagementGroup] = []

  /// The Azure subscription associated with the resource.
  public var subscription: AzureMetadata.AzureSubscription? = nil

  /// The Azure resource group associated with the resource.
  public var resourceGroup: AzureMetadata.AzureResourceGroup? = nil

  /// The Azure Entra tenant associated with the resource.
  public var tenant: AzureMetadata.AzureTenant? = nil

  /// Initialize a new instance of `AzureMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureMetadata().with { $0.managementGroups = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents an Azure management group.
  public struct AzureManagementGroup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The UUID of the Azure management group, for example,
    /// `20000000-0001-0000-0000-000000000000`.
    public var id: Swift.String = Swift.String()

    /// The display name of the Azure management group.
    public var displayName: Swift.String = Swift.String()

    /// Initialize a new instance of `AzureManagementGroup`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AzureManagementGroup().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.AzureMetadata.AzureManagementGroup"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Represents an Azure subscription.
  public struct AzureSubscription: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The UUID of the Azure subscription, for example,
    /// `291bba3f-e0a5-47bc-a099-3bdcb2a50a05`.
    public var id: Swift.String = Swift.String()

    /// The display name of the Azure subscription.
    public var displayName: Swift.String = Swift.String()

    /// Initialize a new instance of `AzureSubscription`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AzureSubscription().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.AzureMetadata.AzureSubscription"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Represents an Azure resource group.
  public struct AzureResourceGroup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The ID of the Azure resource group.
    public var id: Swift.String = Swift.String()

    /// The name of the Azure resource group. This is not a UUID.
    public var name: Swift.String = Swift.String()

    /// Initialize a new instance of `AzureResourceGroup`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AzureResourceGroup().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.AzureMetadata.AzureResourceGroup"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Represents a Microsoft Entra tenant.
  public struct AzureTenant: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The ID of the Microsoft Entra tenant, for example,
    /// "a11aaa11-aa11-1aa1-11aa-1aaa11a".
    public var id: Swift.String = Swift.String()

    /// The display name of the Azure tenant.
    public var displayName: Swift.String = Swift.String()

    /// Initialize a new instance of `AzureTenant`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AzureTenant().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.AzureMetadata.AzureTenant"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.AzureMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
