// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Information related to Google Cloud Backup and DR Service findings.
public struct BackupDisasterRecovery: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of a Backup and DR template which comprises one or more backup
  /// policies. See the [Backup and DR
  /// documentation](https://cloud.google.com/backup-disaster-recovery/docs/concepts/backup-plan#temp)
  /// for more information. For example, `snap-ov`.
  public var backupTemplate: Swift.String = Swift.String()

  /// The names of Backup and DR policies that are associated with a template
  /// and that define when to run a backup, how frequently to run a backup, and
  /// how long to retain the backup image. For example, `onvaults`.
  public var policies: [Swift.String] = []

  /// The name of a Backup and DR host, which is managed by the backup and
  /// recovery appliance and known to the management console. The host can be of
  /// type Generic (for example, Compute Engine, SQL Server, Oracle DB, SMB file
  /// system, etc.), vCenter, or an ESX server. See the [Backup and DR
  /// documentation on
  /// hosts](https://cloud.google.com/backup-disaster-recovery/docs/configuration/manage-hosts-and-their-applications)
  /// for more information. For example, `centos7-01`.
  public var host: Swift.String = Swift.String()

  /// The names of Backup and DR applications. An application is a VM, database,
  /// or file system on a managed host monitored by a backup and recovery
  /// appliance. For example, `centos7-01-vol00`, `centos7-01-vol01`,
  /// `centos7-01-vol02`.
  public var applications: [Swift.String] = []

  /// The name of the Backup and DR storage pool that the backup and recovery
  /// appliance is storing data in. The storage pool could be of type Cloud,
  /// Primary, Snapshot, or OnVault. See the [Backup and DR documentation on
  /// storage
  /// pools](https://cloud.google.com/backup-disaster-recovery/docs/concepts/storage-pools).
  /// For example, `DiskPoolOne`.
  public var storagePool: Swift.String = Swift.String()

  /// The names of Backup and DR advanced policy options of a policy applying to
  /// an application. See the [Backup and DR documentation on policy
  /// options](https://cloud.google.com/backup-disaster-recovery/docs/create-plan/policy-settings).
  /// For example, `skipofflineappsincongrp, nounmap`.
  public var policyOptions: [Swift.String] = []

  /// The name of the Backup and DR resource profile that specifies the storage
  /// media for backups of application and VM data. See the [Backup and DR
  /// documentation on
  /// profiles](https://cloud.google.com/backup-disaster-recovery/docs/concepts/backup-plan#profile).
  /// For example, `GCP`.
  public var profile: Swift.String = Swift.String()

  /// The name of the Backup and DR appliance that captures, moves, and manages
  /// the lifecycle of backup data. For example, `backup-server-57137`.
  public var appliance: Swift.String = Swift.String()

  /// The backup type of the Backup and DR image.
  /// For example, `Snapshot`, `Remote Snapshot`, `OnVault`.
  public var backupType: Swift.String = Swift.String()

  /// The timestamp at which the Backup and DR backup was created.
  public var backupCreateTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupDisasterRecovery`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupDisasterRecovery().with { $0.backupTemplate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backupTemplate = CodingKeys(stringValue: "backupTemplate")
    static let policies = CodingKeys(stringValue: "policies")
    static let host = CodingKeys(stringValue: "host")
    static let applications = CodingKeys(stringValue: "applications")
    static let storagePool = CodingKeys(stringValue: "storagePool")
    static let policyOptions = CodingKeys(stringValue: "policyOptions")
    static let profile = CodingKeys(stringValue: "profile")
    static let appliance = CodingKeys(stringValue: "appliance")
    static let backupType = CodingKeys(stringValue: "backupType")
    static let backupCreateTime = CodingKeys(stringValue: "backupCreateTime")

    static let _knownKeys: Set<Swift.String> = [
      "backupTemplate",
      "policies",
      "host",
      "applications",
      "storagePool",
      "policyOptions",
      "profile",
      "appliance",
      "backupType",
      "backupCreateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupTemplate) {
      self.backupTemplate = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .policies) {
      self.policies = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .host) {
      self.host = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .applications) {
      self.applications = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .storagePool) {
      self.storagePool = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .policyOptions) {
      self.policyOptions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .profile) {
      self.profile = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appliance) {
      self.appliance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupType) {
      self.backupType = value
    }
    self.backupCreateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .backupCreateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.backupTemplate, forKey: .backupTemplate)
    try container.encode(self.policies, forKey: .policies)
    try container.encode(self.host, forKey: .host)
    try container.encode(self.applications, forKey: .applications)
    try container.encode(self.storagePool, forKey: .storagePool)
    try container.encode(self.policyOptions, forKey: .policyOptions)
    try container.encode(self.profile, forKey: .profile)
    try container.encode(self.appliance, forKey: .appliance)
    try container.encode(self.backupType, forKey: .backupType)
    try container.encodeIfPresent(self.backupCreateTime, forKey: .backupCreateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.BackupDisasterRecovery"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
