// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Fields related to Google Cloud Armor findings.
public struct CloudArmor: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Information about the [Google Cloud Armor security
  /// policy](https://cloud.google.com/armor/docs/security-policy-overview)
  /// relevant to the finding.
  public var securityPolicy: SecurityPolicy? = nil

  /// Information about incoming requests evaluated by [Google Cloud Armor
  /// security
  /// policies](https://cloud.google.com/armor/docs/security-policy-overview).
  public var requests: Requests? = nil

  /// Information about potential Layer 7 DDoS attacks identified by [Google
  /// Cloud Armor Adaptive
  /// Protection](https://cloud.google.com/armor/docs/adaptive-protection-overview).
  public var adaptiveProtection: AdaptiveProtection? = nil

  /// Information about DDoS attack volume and classification.
  public var attack: Attack? = nil

  /// Distinguish between volumetric & protocol DDoS attack and
  /// application layer attacks. For example, "L3_4" for Layer 3 and Layer 4 DDoS
  /// attacks, or "L_7" for Layer 7 DDoS attacks.
  public var threatVector: Swift.String = Swift.String()

  /// Duration of attack from the start until the current moment (updated every 5
  /// minutes).
  public var duration: GoogleCloudWKT.Duration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudArmor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudArmor().with { $0.securityPolicy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let securityPolicy = CodingKeys(stringValue: "securityPolicy")
    static let requests = CodingKeys(stringValue: "requests")
    static let adaptiveProtection = CodingKeys(stringValue: "adaptiveProtection")
    static let attack = CodingKeys(stringValue: "attack")
    static let threatVector = CodingKeys(stringValue: "threatVector")
    static let duration = CodingKeys(stringValue: "duration")

    static let _knownKeys: Set<Swift.String> = [
      "securityPolicy",
      "requests",
      "adaptiveProtection",
      "attack",
      "threatVector",
      "duration",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.securityPolicy = try container.decodeIfPresent(
      SecurityPolicy.self, forKey: .securityPolicy)
    self.requests = try container.decodeIfPresent(Requests.self, forKey: .requests)
    self.adaptiveProtection = try container.decodeIfPresent(
      AdaptiveProtection.self, forKey: .adaptiveProtection)
    self.attack = try container.decodeIfPresent(Attack.self, forKey: .attack)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .threatVector) {
      self.threatVector = value
    }
    self.duration = try container.decodeIfPresent(GoogleCloudWKT.Duration.self, forKey: .duration)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.securityPolicy, forKey: .securityPolicy)
    try container.encodeIfPresent(self.requests, forKey: .requests)
    try container.encodeIfPresent(self.adaptiveProtection, forKey: .adaptiveProtection)
    try container.encodeIfPresent(self.attack, forKey: .attack)
    try container.encode(self.threatVector, forKey: .threatVector)
    try container.encodeIfPresent(self.duration, forKey: .duration)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.CloudArmor"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
