// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Metadata taken from a [Cloud Logging
/// LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry)
public struct CloudLoggingEntry: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// A unique identifier for the log entry.
  public var insertId: Swift.String = Swift.String()

  /// The type of the log (part of `log_name`. `log_name` is the resource name of
  /// the log to which this log entry belongs). For example:
  /// `cloudresourcemanager.googleapis.com/activity` Note that this field is not
  /// URL-encoded, unlike in `LogEntry`.
  public var logId: Swift.String = Swift.String()

  /// The organization, folder, or project of the monitored resource that
  /// produced this log entry.
  public var resourceContainer: Swift.String = Swift.String()

  /// The time the event described by the log entry occurred.
  public var timestamp: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudLoggingEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudLoggingEntry().with { $0.insertId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let insertId = CodingKeys(stringValue: "insertId")
    static let logId = CodingKeys(stringValue: "logId")
    static let resourceContainer = CodingKeys(stringValue: "resourceContainer")
    static let timestamp = CodingKeys(stringValue: "timestamp")

    static let _knownKeys: Set<Swift.String> = [
      "insertId",
      "logId",
      "resourceContainer",
      "timestamp",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .insertId) {
      self.insertId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logId) {
      self.logId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceContainer) {
      self.resourceContainer = value
    }
    self.timestamp = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .timestamp)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.insertId, forKey: .insertId)
    try container.encode(self.logId, forKey: .logId)
    try container.encode(self.resourceContainer, forKey: .resourceContainer)
    try container.encodeIfPresent(self.timestamp, forKey: .timestamp)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.CloudLoggingEntry"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
