// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Fields related to Google Cloud Armor findings.
public struct CloudArmor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Information about the [Google Cloud Armor security
  /// policy](https://cloud.google.com/armor/docs/security-policy-overview)
  /// relevant to the finding.
  public var securityPolicy: SecurityPolicy? = nil

  /// Information about incoming requests evaluated by [Google Cloud Armor
  /// security
  /// policies](https://cloud.google.com/armor/docs/security-policy-overview).
  public var requests: Requests? = nil

  /// Information about potential Layer 7 DDoS attacks identified by [Google
  /// Cloud Armor Adaptive
  /// Protection](https://cloud.google.com/armor/docs/adaptive-protection-overview).
  public var adaptiveProtection: AdaptiveProtection? = nil

  /// Information about DDoS attack volume and classification.
  public var attack: Attack? = nil

  /// Distinguish between volumetric & protocol DDoS attack and
  /// application layer attacks. For example, "L3_4" for Layer 3 and Layer 4 DDoS
  /// attacks, or "L_7" for Layer 7 DDoS attacks.
  public var threatVector: Swift.String = Swift.String()

  /// Duration of attack from the start until the current moment (updated every 5
  /// minutes).
  public var duration: GoogleCloudWkt.Duration? = nil

  /// Initialize a new instance of `CloudArmor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudArmor().with { $0.securityPolicy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.CloudArmor"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
