// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Contains information about the IP connection associated with the finding.
public struct Connection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Destination IP address. Not present for sockets that are listening and not
  /// connected.
  public var destinationIp: Swift.String = Swift.String()

  /// Destination port. Not present for sockets that are listening and not
  /// connected.
  public var destinationPort: Swift.Int32 = Swift.Int32()

  /// Source IP address.
  public var sourceIp: Swift.String = Swift.String()

  /// Source port.
  public var sourcePort: Swift.Int32 = Swift.Int32()

  /// IANA Internet Protocol Number such as TCP(6) and UDP(17).
  public var `protocol`: Connection.Protocol_ = Connection.Protocol_()

  /// Initialize a new instance of `Connection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connection().with { $0.destinationIp = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case destinationIp = "destinationIp"
    case destinationPort = "destinationPort"
    case sourceIp = "sourceIp"
    case sourcePort = "sourcePort"
    case `protocol` = "protocol"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.destinationIp = try container.decode(Swift.String.self, forKey: .destinationIp)
    self.destinationPort = try container.decode(Swift.Int32.self, forKey: .destinationPort)
    self.sourceIp = try container.decode(Swift.String.self, forKey: .sourceIp)
    self.sourcePort = try container.decode(Swift.Int32.self, forKey: .sourcePort)
    self.`protocol` = try container.decode(Connection.Protocol_.self, forKey: .`protocol`)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.destinationIp, forKey: .destinationIp)
    try container.encode(self.destinationPort, forKey: .destinationPort)
    try container.encode(self.sourceIp, forKey: .sourceIp)
    try container.encode(self.sourcePort, forKey: .sourcePort)
    try container.encode(self.`protocol`, forKey: .`protocol`)
  }

  /// IANA Internet Protocol Number such as TCP(6) and UDP(17).
  public enum Protocol_: Codable, Equatable, Sendable {
    /// Unspecified protocol (not HOPOPT).
    case unspecified
    /// Internet Control Message Protocol.
    case icmp
    /// Transmission Control Protocol.
    case tcp
    /// User Datagram Protocol.
    case udp
    /// Generic Routing Encapsulation.
    case gre
    /// Encap Security Payload.
    case esp
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .icmp: return 1
      case .tcp: return 6
      case .udp: return 17
      case .gre: return 47
      case .esp: return 50
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROTOCOL_UNSPECIFIED"
      case .icmp: return "ICMP"
      case .tcp: return "TCP"
      case .udp: return "UDP"
      case .gre: return "GRE"
      case .esp: return "ESP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Protocol_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROTOCOL_UNSPECIFIED": self = .unspecified
      case "ICMP": self = .icmp
      case "TCP": self = .tcp
      case "UDP": self = .udp
      case "GRE": self = .gre
      case "ESP": self = .esp
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Protocol_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .icmp
      case 6: self = .tcp
      case 17: self = .udp
      case 47: self = .gre
      case 50: self = .esp
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .icmp: return try container.encode(1)
      case .tcp: return try container.encode(6)
      case .udp: return try container.encode(17)
      case .gre: return try container.encode(47)
      case .esp: return try container.encode(50)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Connection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
