// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for creating a notification config.
public struct CreateNotificationConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Resource name of the new notification config's parent. Its format
  /// is `organizations/[organization_id]/locations/[location_id]`,
  /// `folders/[folder_id]/locations/[location_id]`, or
  /// `projects/[project_id]/locations/[location_id]`.
  public var parent: Swift.String = Swift.String()

  /// Required.
  /// Unique identifier provided by the client within the parent scope.
  /// It must be between 1 and 128 characters and contain alphanumeric
  /// characters, underscores, or hyphens only.
  public var configId: Swift.String = Swift.String()

  /// Required. The notification config being created. The name and the service
  /// account will be ignored as they are both output only fields on this
  /// resource.
  public var notificationConfig: NotificationConfig? = nil

  /// Initialize a new instance of `CreateNotificationConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateNotificationConfigRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.CreateNotificationConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
