// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// CVE stands for Common Vulnerabilities and Exposures.
/// Information from the [CVE
/// record](https://www.cve.org/ResourcesSupport/Glossary) that describes this
/// vulnerability.
public struct Cve: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The unique identifier for the vulnerability. e.g. CVE-2021-34527
  public var id: Swift.String = Swift.String()

  /// Additional information about the CVE.
  /// e.g. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-34527
  public var references: [Reference] = []

  /// Describe Common Vulnerability Scoring System specified at
  /// https://www.first.org/cvss/v3.1/specification-document
  public var cvssv3: Cvssv3? = nil

  /// Whether upstream fix is available for the CVE.
  public var upstreamFixAvailable: Swift.Bool = Swift.Bool()

  /// The potential impact of the vulnerability if it was to be exploited.
  public var impact: Cve.RiskRating = Cve.RiskRating()

  /// The exploitation activity of the vulnerability in the wild.
  public var exploitationActivity: Cve.ExploitationActivity = Cve.ExploitationActivity()

  /// Whether or not the vulnerability has been observed in the wild.
  public var observedInTheWild: Swift.Bool = Swift.Bool()

  /// Whether or not the vulnerability was zero day when the finding was
  /// published.
  public var zeroDay: Swift.Bool = Swift.Bool()

  /// Date the first publicly available exploit or PoC was released.
  public var exploitReleaseDate: GoogleCloudWkt.Timestamp? = nil

  /// Date of the earliest known exploitation.
  public var firstExploitationDate: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `Cve`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cve().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible values of impact of the vulnerability if it was to be
  /// exploited.
  public enum RiskRating: Codable, Equatable, Sendable {
    /// Invalid or empty value.
    case unspecified
    /// Exploitation would have little to no security impact.
    case low
    /// Exploitation would enable attackers to perform activities, or could allow
    /// attackers to have a direct impact, but would require additional steps.
    case medium
    /// Exploitation would enable attackers to have a notable direct impact
    /// without needing to overcome any major mitigating factors.
    case high
    /// Exploitation would fundamentally undermine the security of affected
    /// systems, enable actors to perform significant attacks with minimal
    /// effort, with little to no mitigating factors to overcome.
    case critical
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .low: return 1
      case .medium: return 2
      case .high: return 3
      case .critical: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RISK_RATING_UNSPECIFIED"
      case .low: return "LOW"
      case .medium: return "MEDIUM"
      case .high: return "HIGH"
      case .critical: return "CRITICAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RiskRating/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RISK_RATING_UNSPECIFIED": self = .unspecified
      case "LOW": self = .low
      case "MEDIUM": self = .medium
      case "HIGH": self = .high
      case "CRITICAL": self = .critical
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RiskRating/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .low
      case 2: self = .medium
      case 3: self = .high
      case 4: self = .critical
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .low: return try container.encode(1)
      case .medium: return try container.encode(2)
      case .high: return try container.encode(3)
      case .critical: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible values of exploitation activity of the vulnerability in the
  /// wild.
  public enum ExploitationActivity: Codable, Equatable, Sendable {
    /// Invalid or empty value.
    case unspecified
    /// Exploitation has been reported or confirmed to widely occur.
    case wide
    /// Limited reported or confirmed exploitation activities.
    case confirmed
    /// Exploit is publicly available.
    case available
    /// No known exploitation activity, but has a high potential for
    /// exploitation.
    case anticipated
    /// No known exploitation activity.
    case noKnown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .wide: return 1
      case .confirmed: return 2
      case .available: return 3
      case .anticipated: return 4
      case .noKnown: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EXPLOITATION_ACTIVITY_UNSPECIFIED"
      case .wide: return "WIDE"
      case .confirmed: return "CONFIRMED"
      case .available: return "AVAILABLE"
      case .anticipated: return "ANTICIPATED"
      case .noKnown: return "NO_KNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExploitationActivity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EXPLOITATION_ACTIVITY_UNSPECIFIED": self = .unspecified
      case "WIDE": self = .wide
      case "CONFIRMED": self = .confirmed
      case "AVAILABLE": self = .available
      case "ANTICIPATED": self = .anticipated
      case "NO_KNOWN": self = .noKnown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExploitationActivity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .wide
      case 2: self = .confirmed
      case 3: self = .available
      case 4: self = .anticipated
      case 5: self = .noKnown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .wide: return try container.encode(1)
      case .confirmed: return try container.encode(2)
      case .available: return try container.encode(3)
      case .anticipated: return try container.encode(4)
      case .noKnown: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Cve"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
