// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The LRO metadata for a ExportFindings request.
public struct ExportFindingsMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Timestamp at which export was started
  public var exportStartTime: GoogleCloudWkt.Timestamp? = nil

  /// The destination to export findings to.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `ExportFindingsMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportFindingsMetadata().with { $0.exportStartTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case exportStartTime = "exportStartTime"
    case bigQueryDestination = "bigQueryDestination"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.exportStartTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .exportStartTime)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let bigQueryDestination = try container.decodeIfPresent(
      BigQueryDestination?.self, forKey: .bigQueryDestination)
    {
      try destinationCheckAndSet(.bigQueryDestination(bigQueryDestination))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.exportStartTime, forKey: .exportStartTime)

    if let choice = self.destination {
      switch choice {
      case .bigQueryDestination(let value):
        try container.encode(value, forKey: .bigQueryDestination)
      }
    }
  }

  /// The destination to export findings to.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Required. The destination big query dataset to export findings to.
    indirect case bigQueryDestination(BigQueryDestination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.ExportFindingsMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
