// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Google Cloud metadata associated with the resource. Only applicable if the
/// finding's cloud provider is Google Cloud.
public struct GcpMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The full resource name of project that the resource belongs to.
  public var project: Swift.String = Swift.String()

  /// The project ID that the resource belongs to.
  public var projectDisplayName: Swift.String = Swift.String()

  /// The full resource name of resource's parent.
  public var parent: Swift.String = Swift.String()

  /// The human readable name of resource's parent.
  public var parentDisplayName: Swift.String = Swift.String()

  /// Output only. Contains a Folder message for each folder in the assets
  /// ancestry. The first folder is the deepest nested folder, and the last
  /// folder is the folder directly under the Organization.
  public var folders: [Folder] = []

  /// The name of the organization that the resource belongs to.
  public var organization: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GcpMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcpMetadata().with { $0.project = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let project = CodingKeys(stringValue: "project")
    static let projectDisplayName = CodingKeys(stringValue: "projectDisplayName")
    static let parent = CodingKeys(stringValue: "parent")
    static let parentDisplayName = CodingKeys(stringValue: "parentDisplayName")
    static let folders = CodingKeys(stringValue: "folders")
    static let organization = CodingKeys(stringValue: "organization")

    static let _knownKeys: Set<Swift.String> = [
      "project",
      "projectDisplayName",
      "parent",
      "parentDisplayName",
      "folders",
      "organization",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
      self.project = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectDisplayName) {
      self.projectDisplayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentDisplayName) {
      self.parentDisplayName = value
    }
    if let value = try container.decodeIfPresent([Folder].self, forKey: .folders) {
      self.folders = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .organization) {
      self.organization = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.project, forKey: .project)
    try container.encode(self.projectDisplayName, forKey: .projectDisplayName)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.parentDisplayName, forKey: .parentDisplayName)
    try container.encode(self.folders, forKey: .folders)
    try container.encode(self.organization, forKey: .organization)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.GcpMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
