// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Google Cloud metadata associated with the resource. Only applicable if the
/// finding's cloud provider is Google Cloud.
public struct GcpMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The full resource name of project that the resource belongs to.
  public var project: Swift.String = Swift.String()

  /// The project ID that the resource belongs to.
  public var projectDisplayName: Swift.String = Swift.String()

  /// The full resource name of resource's parent.
  public var parent: Swift.String = Swift.String()

  /// The human readable name of resource's parent.
  public var parentDisplayName: Swift.String = Swift.String()

  /// Output only. Contains a Folder message for each folder in the assets
  /// ancestry. The first folder is the deepest nested folder, and the last
  /// folder is the folder directly under the Organization.
  public var folders: [Folder] = []

  /// The name of the organization that the resource belongs to.
  public var organization: Swift.String = Swift.String()

  /// Initialize a new instance of `GcpMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcpMetadata().with { $0.project = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.GcpMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
