// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents what's commonly known as an _indicator of compromise_ (IoC) in
/// computer forensics. This is an artifact observed on a network or in an
/// operating system that, with high confidence, indicates a computer intrusion.
/// For more information, see [Indicator of
/// compromise](https://en.wikipedia.org/wiki/Indicator_of_compromise).
public struct Indicator: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of IP addresses that are associated with the finding.
  public var ipAddresses: [Swift.String] = []

  /// List of domains associated to the Finding.
  public var domains: [Swift.String] = []

  /// The list of matched signatures indicating that the given
  /// process is present in the environment.
  public var signatures: [Indicator.ProcessSignature] = []

  /// The list of URIs associated to the Findings.
  public var uris: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Indicator`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Indicator().with { $0.ipAddresses = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ipAddresses = CodingKeys(stringValue: "ipAddresses")
    static let domains = CodingKeys(stringValue: "domains")
    static let signatures = CodingKeys(stringValue: "signatures")
    static let uris = CodingKeys(stringValue: "uris")

    static let _knownKeys: Set<Swift.String> = [
      "ipAddresses",
      "domains",
      "signatures",
      "uris",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .ipAddresses) {
      self.ipAddresses = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .domains) {
      self.domains = value
    }
    if let value = try container.decodeIfPresent(
      [Indicator.ProcessSignature].self, forKey: .signatures)
    {
      self.signatures = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .uris) {
      self.uris = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ipAddresses, forKey: .ipAddresses)
    try container.encode(self.domains, forKey: .domains)
    try container.encode(self.signatures, forKey: .signatures)
    try container.encode(self.uris, forKey: .uris)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Indicates what signature matched this process.
  public struct ProcessSignature: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Describes the type of resource associated with the signature.
    public var signatureType: Indicator.ProcessSignature.SignatureType = Indicator.ProcessSignature
      .SignatureType()

    /// The signature.
    public var signature: OneOf_Signature? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ProcessSignature`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProcessSignature().with { $0.memoryHashSignature = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let memoryHashSignature = CodingKeys(stringValue: "memoryHashSignature")
      static let yaraRuleSignature = CodingKeys(stringValue: "yaraRuleSignature")
      static let signatureType = CodingKeys(stringValue: "signatureType")

      static let _knownKeys: Set<Swift.String> = [
        "memoryHashSignature",
        "yaraRuleSignature",
        "signatureType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Indicator.ProcessSignature.SignatureType.self, forKey: .signatureType)
      {
        self.signatureType = value
      }

      var signature: OneOf_Signature? = nil
      let signatureCheckAndSet = {
        if signature != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'signature'"))
        }
        signature = $0
      }
      if let memoryHashSignature = try container.decodeIfPresent(
        Indicator.ProcessSignature.MemoryHashSignature?.self, forKey: .memoryHashSignature)
      {
        try signatureCheckAndSet(.memoryHashSignature(memoryHashSignature))
      }
      if let yaraRuleSignature = try container.decodeIfPresent(
        Indicator.ProcessSignature.YaraRuleSignature?.self, forKey: .yaraRuleSignature)
      {
        try signatureCheckAndSet(.yaraRuleSignature(yaraRuleSignature))
      }
      self.signature = signature
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.signatureType, forKey: .signatureType)

      if let choice = self.signature {
        switch choice {
        case .memoryHashSignature(let value):
          try container.encode(value, forKey: .memoryHashSignature)
        case .yaraRuleSignature(let value):
          try container.encode(value, forKey: .yaraRuleSignature)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// A signature corresponding to memory page hashes.
    public struct MemoryHashSignature: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The binary family.
      public var binaryFamily: Swift.String = Swift.String()

      /// The list of memory hash detections contributing to the binary family
      /// match.
      public var detections: [Indicator.ProcessSignature.MemoryHashSignature.Detection] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `MemoryHashSignature`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MemoryHashSignature().with { $0.binaryFamily = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let binaryFamily = CodingKeys(stringValue: "binaryFamily")
        static let detections = CodingKeys(stringValue: "detections")

        static let _knownKeys: Set<Swift.String> = [
          "binaryFamily",
          "detections",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .binaryFamily) {
          self.binaryFamily = value
        }
        if let value = try container.decodeIfPresent(
          [Indicator.ProcessSignature.MemoryHashSignature.Detection].self, forKey: .detections)
        {
          self.detections = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.binaryFamily, forKey: .binaryFamily)
        try container.encode(self.detections, forKey: .detections)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Memory hash detection contributing to the binary family match.
      public struct Detection: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// The name of the binary associated with the memory hash
        /// signature detection.
        public var binary: Swift.String = Swift.String()

        /// The percentage of memory page hashes in the signature
        /// that were matched.
        public var percentPagesMatched: Swift.Double = Swift.Double()

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `Detection`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Detection().with { $0.binary = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let binary = CodingKeys(stringValue: "binary")
          static let percentPagesMatched = CodingKeys(stringValue: "percentPagesMatched")

          static let _knownKeys: Set<Swift.String> = [
            "binary",
            "percentPagesMatched",
          ]
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(Swift.String.self, forKey: .binary) {
            self.binary = value
          }
          if let value = try container.decodeIfPresent(
            Swift.Double.self, forKey: .percentPagesMatched)
          {
            self.percentPagesMatched = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.WKTValue.self, forKey: key)
          }
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.binary, forKey: .binary)
          try container.encode(self.percentPagesMatched, forKey: .percentPagesMatched)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.securitycenter.v2.Indicator.ProcessSignature.MemoryHashSignature.Detection"
        }
        public init(fromAny any: GoogleWKT.WKTAny) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleWKT.WKTStruct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.securitycenter.v2.Indicator.ProcessSignature.MemoryHashSignature"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// A signature corresponding to a YARA rule.
    public struct YaraRuleSignature: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The name of the YARA rule.
      public var yaraRule: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `YaraRuleSignature`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = YaraRuleSignature().with { $0.yaraRule = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let yaraRule = CodingKeys(stringValue: "yaraRule")

        static let _knownKeys: Set<Swift.String> = [
          "yaraRule"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .yaraRule) {
          self.yaraRule = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.yaraRule, forKey: .yaraRule)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.securitycenter.v2.Indicator.ProcessSignature.YaraRuleSignature"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Possible resource types to be associated with a signature.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SignatureType: Codable, Equatable, Sendable {
      /// The default signature type.
      case unspecified
      /// Used for signatures concerning processes.
      case process
      /// Used for signatures concerning disks.
      case file
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .process: return 1
        case .file: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SIGNATURE_TYPE_UNSPECIFIED"
        case .process: return "SIGNATURE_TYPE_PROCESS"
        case .file: return "SIGNATURE_TYPE_FILE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SignatureType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SIGNATURE_TYPE_UNSPECIFIED": self = .unspecified
        case "SIGNATURE_TYPE_PROCESS": self = .process
        case "SIGNATURE_TYPE_FILE": self = .file
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SignatureType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .process
        case 2: self = .file
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("SIGNATURE_TYPE_UNSPECIFIED")
        case .process: return try container.encode("SIGNATURE_TYPE_PROCESS")
        case .file: return try container.encode("SIGNATURE_TYPE_FILE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The signature.
    public enum OneOf_Signature: Codable, Equatable, Sendable {
      /// Signature indicating that a binary family was matched.
      indirect case memoryHashSignature(Indicator.ProcessSignature.MemoryHashSignature?)
      /// Signature indicating that a YARA rule was matched.
      indirect case yaraRuleSignature(Indicator.ProcessSignature.YaraRuleSignature?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.Indicator.ProcessSignature"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Indicator"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
