// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// IP rule information.
public struct IpRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The IP protocol this rule applies to. This value can either be one of the
  /// following well known protocol strings (TCP, UDP, ICMP, ESP, AH, IPIP,
  /// SCTP) or a string representation of the integer value.
  public var `protocol`: Swift.String = Swift.String()

  /// Optional. An optional list of ports to which this rule applies. This field
  /// is only applicable for the UDP or (S)TCP protocols. Each entry must be
  /// either an integer or a range including a min and max port number.
  public var portRanges: [IpRule.PortRange] = []

  /// Initialize a new instance of `IpRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IpRule().with { $0.`protocol` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `protocol` = "protocol"
    case portRanges = "portRanges"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`protocol` = try container.decode(Swift.String.self, forKey: .`protocol`)
    self.portRanges = try container.decode([IpRule.PortRange].self, forKey: .portRanges)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.portRanges, forKey: .portRanges)
  }

  /// A port range which is inclusive of the min and max values.
  /// Values are between 0 and 2^16-1. The max can be equal / must be not smaller
  /// than the min value. If min and max are equal this indicates that it is a
  /// single port.
  public struct PortRange: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Minimum port value.
    public var min: Swift.Int64 = Swift.Int64()

    /// Maximum port value.
    public var max: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `PortRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PortRange().with { $0.min = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.IpRule.PortRange"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.IpRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
