// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// IP rules associated with the finding.
public struct IpRules: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The direction that the rule is applicable to, one of ingress or egress.
  public var direction: IpRules.Direction = IpRules.Direction()

  /// If source IP ranges are specified, the firewall rule applies only to
  /// traffic that has a source IP address in these ranges. These ranges must be
  /// expressed in CIDR format. Only supports IPv4.
  public var sourceIpRanges: [Swift.String] = []

  /// If destination IP ranges are specified, the firewall rule applies only to
  /// traffic that has a destination IP address in these ranges. These ranges
  /// must be expressed in CIDR format. Only supports IPv4.
  public var destinationIpRanges: [Swift.String] = []

  /// Name of the network protocol service, such as FTP, that is exposed by the
  /// open port. Follows the naming convention available at:
  /// https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml.
  public var exposedServices: [Swift.String] = []

  /// The list of allow rules specified by this firewall. Each rule specifies a
  /// protocol and port-range tuple that describes a permitted connection.
  public var rules: OneOf_Rules? = nil

  /// Initialize a new instance of `IpRules`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IpRules().with { $0.direction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case direction = "direction"
    case allowed = "allowed"
    case denied = "denied"
    case sourceIpRanges = "sourceIpRanges"
    case destinationIpRanges = "destinationIpRanges"
    case exposedServices = "exposedServices"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.direction = try container.decode(IpRules.Direction.self, forKey: .direction)
    self.sourceIpRanges = try container.decode([Swift.String].self, forKey: .sourceIpRanges)
    self.destinationIpRanges = try container.decode(
      [Swift.String].self, forKey: .destinationIpRanges)
    self.exposedServices = try container.decode([Swift.String].self, forKey: .exposedServices)

    var rules: OneOf_Rules? = nil
    let rulesCheckAndSet = {
      if rules != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'rules'"))
      }
      rules = $0
    }
    if let allowed = try container.decodeIfPresent(Allowed?.self, forKey: .allowed) {
      try rulesCheckAndSet(.allowed(allowed))
    }
    if let denied = try container.decodeIfPresent(Denied?.self, forKey: .denied) {
      try rulesCheckAndSet(.denied(denied))
    }
    self.rules = rules
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.direction, forKey: .direction)
    try container.encode(self.sourceIpRanges, forKey: .sourceIpRanges)
    try container.encode(self.destinationIpRanges, forKey: .destinationIpRanges)
    try container.encode(self.exposedServices, forKey: .exposedServices)

    if let choice = self.rules {
      switch choice {
      case .allowed(let value):
        try container.encode(value, forKey: .allowed)
      case .denied(let value):
        try container.encode(value, forKey: .denied)
      }
    }
  }

  /// The type of direction that the rule is applicable to, one of ingress or
  /// egress. Not applicable to OPEN_X_PORT findings.
  public enum Direction: Codable, Equatable, Sendable {
    /// Unspecified direction value.
    case unspecified
    /// Ingress direction value.
    case ingress
    /// Egress direction value.
    case egress
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ingress: return 1
      case .egress: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DIRECTION_UNSPECIFIED"
      case .ingress: return "INGRESS"
      case .egress: return "EGRESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Direction/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DIRECTION_UNSPECIFIED": self = .unspecified
      case "INGRESS": self = .ingress
      case "EGRESS": self = .egress
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Direction/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ingress
      case 2: self = .egress
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ingress: return try container.encode(1)
      case .egress: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The list of allow rules specified by this firewall. Each rule specifies a
  /// protocol and port-range tuple that describes a permitted connection.
  public enum OneOf_Rules: Codable, Equatable, Sendable {
    /// Tuple with allowed rules.
    indirect case allowed(Allowed?)
    /// Tuple with denied rules.
    indirect case denied(Denied?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.IpRules"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
