// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes a job
public struct Job: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The fully-qualified name for a job.
  /// e.g. `projects/<project_id>/jobs/<job_id>`
  public var name: Swift.String = Swift.String()

  /// Output only. State of the job, such as `RUNNING` or `PENDING`.
  public var state: JobState = JobState()

  /// Optional. If the job did not complete successfully, this field describes
  /// why.
  public var errorCode: Swift.Int32 = Swift.Int32()

  /// Optional. Gives the location where the job ran, such as `US` or
  /// `europe-west1`
  public var location: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Job`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Job().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let state = CodingKeys(stringValue: "state")
    static let errorCode = CodingKeys(stringValue: "errorCode")
    static let location = CodingKeys(stringValue: "location")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "state",
      "errorCode",
      "location",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(JobState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .errorCode) {
      self.errorCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.errorCode, forKey: .errorCode)
    try container.encode(self.location, forKey: .location)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Job"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
