// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Kernel mode rootkit signatures.
public struct KernelRootkit: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Rootkit name, when available.
  public var name: Swift.String = Swift.String()

  /// True if unexpected modifications of kernel code memory are present.
  public var unexpectedCodeModification: Swift.Bool = Swift.Bool()

  /// True if unexpected modifications of kernel read-only data memory are
  /// present.
  public var unexpectedReadOnlyDataModification: Swift.Bool = Swift.Bool()

  /// True if `ftrace` points are present with callbacks pointing to regions
  /// that are not in the expected kernel or module code range.
  public var unexpectedFtraceHandler: Swift.Bool = Swift.Bool()

  /// True if `kprobe` points are present with callbacks pointing to regions
  /// that are not in the expected kernel or module code range.
  public var unexpectedKprobeHandler: Swift.Bool = Swift.Bool()

  /// True if kernel code pages that are not in the expected kernel or module
  /// code regions are present.
  public var unexpectedKernelCodePages: Swift.Bool = Swift.Bool()

  /// True if system call handlers that are are not in the expected kernel or
  /// module code regions are present.
  public var unexpectedSystemCallHandler: Swift.Bool = Swift.Bool()

  /// True if interrupt handlers that are are not in the expected kernel or
  /// module code regions are present.
  public var unexpectedInterruptHandler: Swift.Bool = Swift.Bool()

  /// True if unexpected processes in the scheduler run queue are present. Such
  /// processes are in the run queue, but not in the process task list.
  public var unexpectedProcessesInRunqueue: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `KernelRootkit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = KernelRootkit().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let unexpectedCodeModification = CodingKeys(stringValue: "unexpectedCodeModification")
    static let unexpectedReadOnlyDataModification = CodingKeys(
      stringValue: "unexpectedReadOnlyDataModification")
    static let unexpectedFtraceHandler = CodingKeys(stringValue: "unexpectedFtraceHandler")
    static let unexpectedKprobeHandler = CodingKeys(stringValue: "unexpectedKprobeHandler")
    static let unexpectedKernelCodePages = CodingKeys(stringValue: "unexpectedKernelCodePages")
    static let unexpectedSystemCallHandler = CodingKeys(stringValue: "unexpectedSystemCallHandler")
    static let unexpectedInterruptHandler = CodingKeys(stringValue: "unexpectedInterruptHandler")
    static let unexpectedProcessesInRunqueue = CodingKeys(
      stringValue: "unexpectedProcessesInRunqueue")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "unexpectedCodeModification",
      "unexpectedReadOnlyDataModification",
      "unexpectedFtraceHandler",
      "unexpectedKprobeHandler",
      "unexpectedKernelCodePages",
      "unexpectedSystemCallHandler",
      "unexpectedInterruptHandler",
      "unexpectedProcessesInRunqueue",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .unexpectedCodeModification)
    {
      self.unexpectedCodeModification = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .unexpectedReadOnlyDataModification)
    {
      self.unexpectedReadOnlyDataModification = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .unexpectedFtraceHandler)
    {
      self.unexpectedFtraceHandler = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .unexpectedKprobeHandler)
    {
      self.unexpectedKprobeHandler = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .unexpectedKernelCodePages)
    {
      self.unexpectedKernelCodePages = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .unexpectedSystemCallHandler)
    {
      self.unexpectedSystemCallHandler = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .unexpectedInterruptHandler)
    {
      self.unexpectedInterruptHandler = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .unexpectedProcessesInRunqueue)
    {
      self.unexpectedProcessesInRunqueue = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.unexpectedCodeModification, forKey: .unexpectedCodeModification)
    try container.encode(
      self.unexpectedReadOnlyDataModification, forKey: .unexpectedReadOnlyDataModification)
    try container.encode(self.unexpectedFtraceHandler, forKey: .unexpectedFtraceHandler)
    try container.encode(self.unexpectedKprobeHandler, forKey: .unexpectedKprobeHandler)
    try container.encode(self.unexpectedKernelCodePages, forKey: .unexpectedKernelCodePages)
    try container.encode(self.unexpectedSystemCallHandler, forKey: .unexpectedSystemCallHandler)
    try container.encode(self.unexpectedInterruptHandler, forKey: .unexpectedInterruptHandler)
    try container.encode(self.unexpectedProcessesInRunqueue, forKey: .unexpectedProcessesInRunqueue)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.KernelRootkit"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
