// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for listing findings.
public struct ListFindingsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Findings matching the list request.
  public var listFindingsResults: [ListFindingsResponse.ListFindingsResult] = []

  /// Token to retrieve the next page of results, or empty if there are no more
  /// results.
  public var nextPageToken: Swift.String = Swift.String()

  /// The total number of findings matching the query.
  public var totalSize: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListFindingsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListFindingsResponse().with { $0.listFindingsResults = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let listFindingsResults = CodingKeys(stringValue: "listFindingsResults")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let totalSize = CodingKeys(stringValue: "totalSize")

    static let _knownKeys: Set<Swift.String> = [
      "listFindingsResults",
      "nextPageToken",
      "totalSize",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [ListFindingsResponse.ListFindingsResult].self, forKey: .listFindingsResults)
    {
      self.listFindingsResults = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalSize) {
      self.totalSize = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.listFindingsResults, forKey: .listFindingsResults)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.totalSize, forKey: .totalSize)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Result containing the Finding.
  public struct ListFindingsResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Finding matching the search request.
    public var finding: Finding? = nil

    /// Output only. Resource that is associated with this finding.
    public var resource: ListFindingsResponse.ListFindingsResult.Resource? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListFindingsResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListFindingsResult().with { $0.finding = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let finding = CodingKeys(stringValue: "finding")
      static let resource = CodingKeys(stringValue: "resource")

      static let _knownKeys: Set<Swift.String> = [
        "finding",
        "resource",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.finding = try container.decodeIfPresent(Finding.self, forKey: .finding)
      self.resource = try container.decodeIfPresent(
        ListFindingsResponse.ListFindingsResult.Resource.self, forKey: .resource)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.finding, forKey: .finding)
      try container.encodeIfPresent(self.resource, forKey: .resource)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Information related to the Google Cloud resource that is
    /// associated with this finding.
    public struct Resource: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The full resource name of the resource. See:
      /// https://cloud.google.com/apis/design/resource_names#full_resource_name
      public var name: Swift.String = Swift.String()

      /// The human readable name of the resource.
      public var displayName: Swift.String = Swift.String()

      /// The full resource type of the resource.
      public var type: Swift.String = Swift.String()

      /// Indicates which cloud provider the finding is from.
      public var cloudProvider: CloudProvider = CloudProvider()

      /// The service or resource provider associated with the resource.
      public var service: Swift.String = Swift.String()

      /// The region or location of the service (if applicable).
      public var location: Swift.String = Swift.String()

      /// Provides the path to the resource within the resource hierarchy.
      public var resourcePath: ResourcePath? = nil

      /// A string representation of the resource path.
      /// For Google Cloud, it has the format of
      /// `organizations/{organization_id}/folders/{folder_id}/folders/{folder_id}/projects/{project_id}`
      /// where there can be any number of folders.
      /// For AWS, it has the format of
      /// `org/{organization_id}/ou/{organizational_unit_id}/ou/{organizational_unit_id}/account/{account_id}`
      /// where there can be any number of organizational units.
      /// For Azure, it has the format of
      /// `mg/{management_group_id}/mg/{management_group_id}/subscription/{subscription_id}/rg/{resource_group_name}`
      /// where there can be any number of management groups.
      public var resourcePathString: Swift.String = Swift.String()

      /// The metadata associated with the cloud provider.
      public var cloudProviderMetadata: OneOf_CloudProviderMetadata? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Resource`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Resource().with { $0.name = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let name = CodingKeys(stringValue: "name")
        static let displayName = CodingKeys(stringValue: "displayName")
        static let type = CodingKeys(stringValue: "type")
        static let cloudProvider = CodingKeys(stringValue: "cloudProvider")
        static let service = CodingKeys(stringValue: "service")
        static let location = CodingKeys(stringValue: "location")
        static let gcpMetadata = CodingKeys(stringValue: "gcpMetadata")
        static let awsMetadata = CodingKeys(stringValue: "awsMetadata")
        static let azureMetadata = CodingKeys(stringValue: "azureMetadata")
        static let resourcePath = CodingKeys(stringValue: "resourcePath")
        static let resourcePathString = CodingKeys(stringValue: "resourcePathString")

        static let _knownKeys: Set<Swift.String> = [
          "name",
          "displayName",
          "type",
          "cloudProvider",
          "service",
          "location",
          "gcpMetadata",
          "awsMetadata",
          "azureMetadata",
          "resourcePath",
          "resourcePathString",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
          self.name = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
          self.displayName = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
          self.type = value
        }
        if let value = try container.decodeIfPresent(CloudProvider.self, forKey: .cloudProvider) {
          self.cloudProvider = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .service) {
          self.service = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
          self.location = value
        }
        self.resourcePath = try container.decodeIfPresent(ResourcePath.self, forKey: .resourcePath)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourcePathString)
        {
          self.resourcePathString = value
        }

        var cloudProviderMetadata: OneOf_CloudProviderMetadata? = nil
        let cloudProviderMetadataCheckAndSet = {
          if cloudProviderMetadata != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'cloudProviderMetadata'"))
          }
          cloudProviderMetadata = $0
        }
        if let gcpMetadata = try container.decodeIfPresent(GcpMetadata?.self, forKey: .gcpMetadata)
        {
          try cloudProviderMetadataCheckAndSet(.gcpMetadata(gcpMetadata))
        }
        if let awsMetadata = try container.decodeIfPresent(AwsMetadata?.self, forKey: .awsMetadata)
        {
          try cloudProviderMetadataCheckAndSet(.awsMetadata(awsMetadata))
        }
        if let azureMetadata = try container.decodeIfPresent(
          AzureMetadata?.self, forKey: .azureMetadata)
        {
          try cloudProviderMetadataCheckAndSet(.azureMetadata(azureMetadata))
        }
        self.cloudProviderMetadata = cloudProviderMetadata
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.displayName, forKey: .displayName)
        try container.encode(self.type, forKey: .type)
        try container.encode(self.cloudProvider, forKey: .cloudProvider)
        try container.encode(self.service, forKey: .service)
        try container.encode(self.location, forKey: .location)
        try container.encodeIfPresent(self.resourcePath, forKey: .resourcePath)
        try container.encode(self.resourcePathString, forKey: .resourcePathString)

        if let choice = self.cloudProviderMetadata {
          switch choice {
          case .gcpMetadata(let value):
            try container.encode(value, forKey: .gcpMetadata)
          case .awsMetadata(let value):
            try container.encode(value, forKey: .awsMetadata)
          case .azureMetadata(let value):
            try container.encode(value, forKey: .azureMetadata)
          }
        }
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The metadata associated with the cloud provider.
      public enum OneOf_CloudProviderMetadata: Codable, Equatable, Sendable {
        /// The GCP metadata associated with the finding.
        indirect case gcpMetadata(GcpMetadata?)
        /// The AWS metadata associated with the finding.
        indirect case awsMetadata(AwsMetadata?)
        /// The Azure metadata associated with the finding.
        indirect case azureMetadata(AzureMetadata?)
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.securitycenter.v2.ListFindingsResponse.ListFindingsResult.Resource"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycenter.v2.ListFindingsResponse.ListFindingsResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.ListFindingsResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListFindingsResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [ListFindingsResponse.ListFindingsResult] {
    return self.listFindingsResults
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
