// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An individual entry in a log.
public struct LogEntry: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The log entry.
  public var logEntry: OneOf_LogEntry? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LogEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogEntry().with { $0.cloudLoggingEntry = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudLoggingEntry = CodingKeys(stringValue: "cloudLoggingEntry")

    static let _knownKeys: Set<Swift.String> = [
      "cloudLoggingEntry"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var logEntry: OneOf_LogEntry? = nil
    let logEntryCheckAndSet = {
      if logEntry != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'logEntry'"))
      }
      logEntry = $0
    }
    if let cloudLoggingEntry = try container.decodeIfPresent(
      CloudLoggingEntry?.self, forKey: .cloudLoggingEntry)
    {
      try logEntryCheckAndSet(.cloudLoggingEntry(cloudLoggingEntry))
    }
    self.logEntry = logEntry
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.logEntry {
      switch choice {
      case .cloudLoggingEntry(let value):
        try container.encode(value, forKey: .cloudLoggingEntry)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The log entry.
  public enum OneOf_LogEntry: Codable, Equatable, Sendable {
    /// An individual entry in a log stored in Cloud Logging.
    indirect case cloudLoggingEntry(CloudLoggingEntry?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.LogEntry"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
