// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents an operating system process.
public struct Process: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The process name, as displayed in utilities like `top` and `ps`. This name
  /// can be accessed through `/proc/[pid]/comm` and changed with
  /// `prctl(PR_SET_NAME)`.
  public var name: Swift.String = Swift.String()

  /// File information for the process executable.
  public var binary: File? = nil

  /// File information for libraries loaded by the process.
  public var libraries: [File] = []

  /// When the process represents the invocation of a script, `binary` provides
  /// information about the interpreter, while `script` provides information
  /// about the script file provided to the interpreter.
  public var script: File? = nil

  /// Process arguments as JSON encoded strings.
  public var args: [Swift.String] = []

  /// True if `args` is incomplete.
  public var argumentsTruncated: Swift.Bool = Swift.Bool()

  /// Process environment variables.
  public var envVariables: [EnvironmentVariable] = []

  /// True if `env_variables` is incomplete.
  public var envVariablesTruncated: Swift.Bool = Swift.Bool()

  /// The process ID.
  public var pid: Swift.Int64 = Swift.Int64()

  /// The parent process ID.
  public var parentPid: Swift.Int64 = Swift.Int64()

  /// The ID of the user that executed the process. E.g. If this is the root user
  /// this will always be 0.
  public var userId: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Process`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Process().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let binary = CodingKeys(stringValue: "binary")
    static let libraries = CodingKeys(stringValue: "libraries")
    static let script = CodingKeys(stringValue: "script")
    static let args = CodingKeys(stringValue: "args")
    static let argumentsTruncated = CodingKeys(stringValue: "argumentsTruncated")
    static let envVariables = CodingKeys(stringValue: "envVariables")
    static let envVariablesTruncated = CodingKeys(stringValue: "envVariablesTruncated")
    static let pid = CodingKeys(stringValue: "pid")
    static let parentPid = CodingKeys(stringValue: "parentPid")
    static let userId = CodingKeys(stringValue: "userId")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "binary",
      "libraries",
      "script",
      "args",
      "argumentsTruncated",
      "envVariables",
      "envVariablesTruncated",
      "pid",
      "parentPid",
      "userId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.binary = try container.decodeIfPresent(File.self, forKey: .binary)
    if let value = try container.decodeIfPresent([File].self, forKey: .libraries) {
      self.libraries = value
    }
    self.script = try container.decodeIfPresent(File.self, forKey: .script)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .args) {
      self.args = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .argumentsTruncated) {
      self.argumentsTruncated = value
    }
    if let value = try container.decodeIfPresent([EnvironmentVariable].self, forKey: .envVariables)
    {
      self.envVariables = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .envVariablesTruncated) {
      self.envVariablesTruncated = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .pid) {
      self.pid = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .parentPid) {
      self.parentPid = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .userId) {
      self.userId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.binary, forKey: .binary)
    try container.encode(self.libraries, forKey: .libraries)
    try container.encodeIfPresent(self.script, forKey: .script)
    try container.encode(self.args, forKey: .args)
    try container.encode(self.argumentsTruncated, forKey: .argumentsTruncated)
    try container.encode(self.envVariables, forKey: .envVariables)
    try container.encode(self.envVariablesTruncated, forKey: .envVariablesTruncated)
    try container.encode(self.pid, forKey: .pid)
    try container.encode(self.parentPid, forKey: .parentPid)
    try container.encode(self.userId, forKey: .userId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Process"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
