// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information about the requests relevant to the finding.
public struct Requests: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// For 'Increasing deny ratio', the ratio is the denied traffic divided by the
  /// allowed traffic. For 'Allowed traffic spike', the ratio is the allowed
  /// traffic in the short term divided by allowed traffic in the long term.
  public var ratio: Swift.Double = Swift.Double()

  /// Allowed RPS (requests per second) in the short term.
  public var shortTermAllowed: Swift.Int32 = Swift.Int32()

  /// Allowed RPS (requests per second) over the long term.
  public var longTermAllowed: Swift.Int32 = Swift.Int32()

  /// Denied RPS (requests per second) over the long term.
  public var longTermDenied: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Requests`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Requests().with { $0.ratio = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ratio = CodingKeys(stringValue: "ratio")
    static let shortTermAllowed = CodingKeys(stringValue: "shortTermAllowed")
    static let longTermAllowed = CodingKeys(stringValue: "longTermAllowed")
    static let longTermDenied = CodingKeys(stringValue: "longTermDenied")

    static let _knownKeys: Set<Swift.String> = [
      "ratio",
      "shortTermAllowed",
      "longTermAllowed",
      "longTermDenied",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .ratio) {
      self.ratio = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .shortTermAllowed) {
      self.shortTermAllowed = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .longTermAllowed) {
      self.longTermAllowed = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .longTermDenied) {
      self.longTermDenied = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ratio, forKey: .ratio)
    try container.encode(self.shortTermAllowed, forKey: .shortTermAllowed)
    try container.encode(self.longTermAllowed, forKey: .longTermAllowed)
    try container.encode(self.longTermDenied, forKey: .longTermDenied)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Requests"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
