// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents the path of resources leading up to the resource this finding is
/// about.
public struct ResourcePath: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The list of nodes that make the up resource path, ordered from lowest
  /// level to highest level.
  public var nodes: [ResourcePath.ResourcePathNode] = []

  /// Initialize a new instance of `ResourcePath`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourcePath().with { $0.nodes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A node within the resource path. Each node represents a resource within the
  /// resource hierarchy.
  public struct ResourcePathNode: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The type of resource this node represents.
    public var nodeType: ResourcePath.ResourcePathNodeType = ResourcePath.ResourcePathNodeType()

    /// The ID of the resource this node represents.
    public var id: Swift.String = Swift.String()

    /// The display name of the resource this node represents.
    public var displayName: Swift.String = Swift.String()

    /// Initialize a new instance of `ResourcePathNode`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourcePathNode().with { $0.nodeType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.ResourcePath.ResourcePathNode"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The type of resource the node represents.
  public enum ResourcePathNodeType: Codable, Equatable, Sendable {
    /// Node type is unspecified.
    case unspecified
    /// The node represents a Google Cloud organization.
    case gcpOrganization
    /// The node represents a Google Cloud folder.
    case gcpFolder
    /// The node represents a Google Cloud project.
    case gcpProject
    /// The node represents an AWS organization.
    case awsOrganization
    /// The node represents an AWS organizational unit.
    case awsOrganizationalUnit
    /// The node represents an AWS account.
    case awsAccount
    /// The node represents an Azure management group.
    case azureManagementGroup
    /// The node represents an Azure subscription.
    case azureSubscription
    /// The node represents an Azure resource group.
    case azureResourceGroup
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .gcpOrganization: return 1
      case .gcpFolder: return 2
      case .gcpProject: return 3
      case .awsOrganization: return 4
      case .awsOrganizationalUnit: return 5
      case .awsAccount: return 6
      case .azureManagementGroup: return 7
      case .azureSubscription: return 8
      case .azureResourceGroup: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESOURCE_PATH_NODE_TYPE_UNSPECIFIED"
      case .gcpOrganization: return "GCP_ORGANIZATION"
      case .gcpFolder: return "GCP_FOLDER"
      case .gcpProject: return "GCP_PROJECT"
      case .awsOrganization: return "AWS_ORGANIZATION"
      case .awsOrganizationalUnit: return "AWS_ORGANIZATIONAL_UNIT"
      case .awsAccount: return "AWS_ACCOUNT"
      case .azureManagementGroup: return "AZURE_MANAGEMENT_GROUP"
      case .azureSubscription: return "AZURE_SUBSCRIPTION"
      case .azureResourceGroup: return "AZURE_RESOURCE_GROUP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResourcePathNodeType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESOURCE_PATH_NODE_TYPE_UNSPECIFIED": self = .unspecified
      case "GCP_ORGANIZATION": self = .gcpOrganization
      case "GCP_FOLDER": self = .gcpFolder
      case "GCP_PROJECT": self = .gcpProject
      case "AWS_ORGANIZATION": self = .awsOrganization
      case "AWS_ORGANIZATIONAL_UNIT": self = .awsOrganizationalUnit
      case "AWS_ACCOUNT": self = .awsAccount
      case "AZURE_MANAGEMENT_GROUP": self = .azureManagementGroup
      case "AZURE_SUBSCRIPTION": self = .azureSubscription
      case "AZURE_RESOURCE_GROUP": self = .azureResourceGroup
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResourcePathNodeType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .gcpOrganization
      case 2: self = .gcpFolder
      case 3: self = .gcpProject
      case 4: self = .awsOrganization
      case 5: self = .awsOrganizationalUnit
      case 6: self = .awsAccount
      case 7: self = .azureManagementGroup
      case 8: self = .azureSubscription
      case 9: self = .azureResourceGroup
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .gcpOrganization: return try container.encode(1)
      case .gcpFolder: return try container.encode(2)
      case .gcpProject: return try container.encode(3)
      case .awsOrganization: return try container.encode(4)
      case .awsOrganizationalUnit: return try container.encode(5)
      case .awsAccount: return try container.encode(6)
      case .azureManagementGroup: return try container.encode(7)
      case .azureSubscription: return try container.encode(8)
      case .azureResourceGroup: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.ResourcePath"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
