// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A resource value configuration (RVC) is a mapping configuration of user's
/// resources to resource values. Used in Attack path simulations.
public struct ResourceValueConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name for the resource value configuration
  public var name: Swift.String = Swift.String()

  /// Resource value level this expression represents
  /// Only required when there is no Sensitive Data Protection mapping in the
  /// request
  public var resourceValue: ResourceValue = ResourceValue()

  /// Tag values combined with `AND` to check against.
  /// For Google Cloud resources, they are tag value IDs in the form of
  /// "tagValues/123". Example: `[ "tagValues/123", "tagValues/456",
  /// "tagValues/789" ]`
  /// https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing
  public var tagValues: [Swift.String] = []

  /// Apply resource_value only to resources that match resource_type.
  /// resource_type will be checked with `AND` of other resources.
  /// For example, "storage.googleapis.com/Bucket" with resource_value "HIGH"
  /// will apply "HIGH" value only to "storage.googleapis.com/Bucket" resources.
  public var resourceType: Swift.String = Swift.String()

  /// Project or folder to scope this configuration to.
  /// For example, "project/456" would apply this configuration only to resources
  /// in "project/456" scope and will be checked with `AND` of other resources.
  public var scope: Swift.String = Swift.String()

  /// List of resource labels to search for, evaluated with `AND`.
  /// For example, "resource_labels_selector": {"key": "value", "env": "prod"}
  /// will match resources with labels "key": "value" `AND` "env":
  /// "prod"
  /// https://cloud.google.com/resource-manager/docs/creating-managing-labels
  public var resourceLabelsSelector: [Swift.String: Swift.String] = [:]

  /// Description of the resource value configuration.
  public var description: Swift.String = Swift.String()

  /// Output only. Timestamp this resource value configuration was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Timestamp this resource value configuration was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Cloud provider this configuration applies to
  public var cloudProvider: CloudProvider = CloudProvider()

  /// A mapping of the sensitivity on Sensitive Data Protection finding to
  /// resource values. This mapping can only be used in combination with a
  /// resource_type that is related to BigQuery, e.g.
  /// "bigquery.googleapis.com/Dataset".
  public var sensitiveDataProtectionMapping: ResourceValueConfig.SensitiveDataProtectionMapping? =
    nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceValueConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceValueConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let resourceValue = CodingKeys(stringValue: "resourceValue")
    static let tagValues = CodingKeys(stringValue: "tagValues")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let scope = CodingKeys(stringValue: "scope")
    static let resourceLabelsSelector = CodingKeys(stringValue: "resourceLabelsSelector")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let cloudProvider = CodingKeys(stringValue: "cloudProvider")
    static let sensitiveDataProtectionMapping = CodingKeys(
      stringValue: "sensitiveDataProtectionMapping")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "resourceValue",
      "tagValues",
      "resourceType",
      "scope",
      "resourceLabelsSelector",
      "description",
      "createTime",
      "updateTime",
      "cloudProvider",
      "sensitiveDataProtectionMapping",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(ResourceValue.self, forKey: .resourceValue) {
      self.resourceValue = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tagValues) {
      self.tagValues = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .scope) {
      self.scope = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .resourceLabelsSelector)
    {
      self.resourceLabelsSelector = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(CloudProvider.self, forKey: .cloudProvider) {
      self.cloudProvider = value
    }
    self.sensitiveDataProtectionMapping = try container.decodeIfPresent(
      ResourceValueConfig.SensitiveDataProtectionMapping.self,
      forKey: .sensitiveDataProtectionMapping)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.resourceValue, forKey: .resourceValue)
    try container.encode(self.tagValues, forKey: .tagValues)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.scope, forKey: .scope)
    try container.encode(self.resourceLabelsSelector, forKey: .resourceLabelsSelector)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.cloudProvider, forKey: .cloudProvider)
    try container.encodeIfPresent(
      self.sensitiveDataProtectionMapping, forKey: .sensitiveDataProtectionMapping)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Resource value mapping for Sensitive Data Protection findings
  /// If any of these mappings have a resource value that is not unspecified,
  /// the resource_value field will be ignored when reading this configuration.
  public struct SensitiveDataProtectionMapping: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Resource value mapping for high-sensitivity Sensitive Data Protection
    /// findings
    public var highSensitivityMapping: ResourceValue = ResourceValue()

    /// Resource value mapping for medium-sensitivity Sensitive Data Protection
    /// findings
    public var mediumSensitivityMapping: ResourceValue = ResourceValue()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SensitiveDataProtectionMapping`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SensitiveDataProtectionMapping().with { $0.highSensitivityMapping = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let highSensitivityMapping = CodingKeys(stringValue: "highSensitivityMapping")
      static let mediumSensitivityMapping = CodingKeys(stringValue: "mediumSensitivityMapping")

      static let _knownKeys: Set<Swift.String> = [
        "highSensitivityMapping",
        "mediumSensitivityMapping",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        ResourceValue.self, forKey: .highSensitivityMapping)
      {
        self.highSensitivityMapping = value
      }
      if let value = try container.decodeIfPresent(
        ResourceValue.self, forKey: .mediumSensitivityMapping)
      {
        self.mediumSensitivityMapping = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.highSensitivityMapping, forKey: .highSensitivityMapping)
      try container.encode(self.mediumSensitivityMapping, forKey: .mediumSensitivityMapping)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycenter.v2.ResourceValueConfig.SensitiveDataProtectionMapping"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.ResourceValueConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
