// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Information related to the Google Cloud resource.
public struct Resource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The full resource name of the resource. See:
  /// https://cloud.google.com/apis/design/resource_names#full_resource_name
  public var name: Swift.String = Swift.String()

  /// The human readable name of the resource.
  public var displayName: Swift.String = Swift.String()

  /// The full resource type of the resource.
  public var type: Swift.String = Swift.String()

  /// Indicates which cloud provider the finding is from.
  public var cloudProvider: CloudProvider = CloudProvider()

  /// The service or resource provider associated with the resource.
  public var service: Swift.String = Swift.String()

  /// The region or location of the service (if applicable).
  public var location: Swift.String = Swift.String()

  /// Provides the path to the resource within the resource hierarchy.
  public var resourcePath: ResourcePath? = nil

  /// A string representation of the resource path.
  /// For Google Cloud, it has the format of
  /// `organizations/{organization_id}/folders/{folder_id}/folders/{folder_id}/projects/{project_id}`
  /// where there can be any number of folders.
  /// For AWS, it has the format of
  /// `org/{organization_id}/ou/{organizational_unit_id}/ou/{organizational_unit_id}/account/{account_id}`
  /// where there can be any number of organizational units.
  /// For Azure, it has the format of
  /// `mg/{management_group_id}/mg/{management_group_id}/subscription/{subscription_id}/rg/{resource_group_name}`
  /// where there can be any number of management groups.
  public var resourcePathString: Swift.String = Swift.String()

  /// The metadata associated with the cloud provider.
  public var cloudProviderMetadata: OneOf_CloudProviderMetadata? = nil

  /// Initialize a new instance of `Resource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Resource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case displayName = "displayName"
    case type = "type"
    case cloudProvider = "cloudProvider"
    case service = "service"
    case location = "location"
    case gcpMetadata = "gcpMetadata"
    case awsMetadata = "awsMetadata"
    case azureMetadata = "azureMetadata"
    case resourcePath = "resourcePath"
    case resourcePathString = "resourcePathString"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.type = try container.decode(Swift.String.self, forKey: .type)
    self.cloudProvider = try container.decode(CloudProvider.self, forKey: .cloudProvider)
    self.service = try container.decode(Swift.String.self, forKey: .service)
    self.location = try container.decode(Swift.String.self, forKey: .location)
    self.resourcePath = try container.decodeIfPresent(ResourcePath.self, forKey: .resourcePath)
    self.resourcePathString = try container.decode(Swift.String.self, forKey: .resourcePathString)

    var cloudProviderMetadata: OneOf_CloudProviderMetadata? = nil
    let cloudProviderMetadataCheckAndSet = {
      if cloudProviderMetadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'cloudProviderMetadata'"))
      }
      cloudProviderMetadata = $0
    }
    if let gcpMetadata = try container.decodeIfPresent(GcpMetadata?.self, forKey: .gcpMetadata) {
      try cloudProviderMetadataCheckAndSet(.gcpMetadata(gcpMetadata))
    }
    if let awsMetadata = try container.decodeIfPresent(AwsMetadata?.self, forKey: .awsMetadata) {
      try cloudProviderMetadataCheckAndSet(.awsMetadata(awsMetadata))
    }
    if let azureMetadata = try container.decodeIfPresent(
      AzureMetadata?.self, forKey: .azureMetadata)
    {
      try cloudProviderMetadataCheckAndSet(.azureMetadata(azureMetadata))
    }
    self.cloudProviderMetadata = cloudProviderMetadata
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.cloudProvider, forKey: .cloudProvider)
    try container.encode(self.service, forKey: .service)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.resourcePath, forKey: .resourcePath)
    try container.encode(self.resourcePathString, forKey: .resourcePathString)

    if let choice = self.cloudProviderMetadata {
      switch choice {
      case .gcpMetadata(let value):
        try container.encode(value, forKey: .gcpMetadata)
      case .awsMetadata(let value):
        try container.encode(value, forKey: .awsMetadata)
      case .azureMetadata(let value):
        try container.encode(value, forKey: .azureMetadata)
      }
    }
  }

  /// The metadata associated with the cloud provider.
  public enum OneOf_CloudProviderMetadata: Codable, Equatable, Sendable {
    /// The GCP metadata associated with the finding.
    indirect case gcpMetadata(GcpMetadata?)
    /// The AWS metadata associated with the finding.
    indirect case awsMetadata(AwsMetadata?)
    /// The Azure metadata associated with the finding.
    indirect case azureMetadata(AzureMetadata?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Resource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
