// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a posture that is deployed on Google Cloud by the
/// Security Command Center Posture Management service.
/// A posture contains one or more policy sets. A policy set is a
/// group of policies that enforce a set of security rules on Google
/// Cloud.
public struct SecurityPosture: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the posture, for example, `CIS-Posture`.
  public var name: Swift.String = Swift.String()

  /// The version of the posture, for example, `c7cfa2a8`.
  public var revisionId: Swift.String = Swift.String()

  /// The project, folder, or organization on which the posture is deployed,
  /// for example, `projects/{project_number}`.
  public var postureDeploymentResource: Swift.String = Swift.String()

  /// The name of the posture deployment, for example,
  /// `organizations/{org_id}/posturedeployments/{posture_deployment_id}`.
  public var postureDeployment: Swift.String = Swift.String()

  /// The name of the updated policy, for example,
  /// `projects/{project_id}/policies/{constraint_name}`.
  public var changedPolicy: Swift.String = Swift.String()

  /// The name of the updated policy set, for example, `cis-policyset`.
  public var policySet: Swift.String = Swift.String()

  /// The ID of the updated policy, for example, `compute-policy-1`.
  public var policy: Swift.String = Swift.String()

  /// The details about a change in an updated policy that violates the deployed
  /// posture.
  public var policyDriftDetails: [SecurityPosture.PolicyDriftDetails] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SecurityPosture`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecurityPosture().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let revisionId = CodingKeys(stringValue: "revisionId")
    static let postureDeploymentResource = CodingKeys(stringValue: "postureDeploymentResource")
    static let postureDeployment = CodingKeys(stringValue: "postureDeployment")
    static let changedPolicy = CodingKeys(stringValue: "changedPolicy")
    static let policySet = CodingKeys(stringValue: "policySet")
    static let policy = CodingKeys(stringValue: "policy")
    static let policyDriftDetails = CodingKeys(stringValue: "policyDriftDetails")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "revisionId",
      "postureDeploymentResource",
      "postureDeployment",
      "changedPolicy",
      "policySet",
      "policy",
      "policyDriftDetails",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .revisionId) {
      self.revisionId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .postureDeploymentResource)
    {
      self.postureDeploymentResource = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .postureDeployment) {
      self.postureDeployment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .changedPolicy) {
      self.changedPolicy = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .policySet) {
      self.policySet = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .policy) {
      self.policy = value
    }
    if let value = try container.decodeIfPresent(
      [SecurityPosture.PolicyDriftDetails].self, forKey: .policyDriftDetails)
    {
      self.policyDriftDetails = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.revisionId, forKey: .revisionId)
    try container.encode(self.postureDeploymentResource, forKey: .postureDeploymentResource)
    try container.encode(self.postureDeployment, forKey: .postureDeployment)
    try container.encode(self.changedPolicy, forKey: .changedPolicy)
    try container.encode(self.policySet, forKey: .policySet)
    try container.encode(self.policy, forKey: .policy)
    try container.encode(self.policyDriftDetails, forKey: .policyDriftDetails)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The policy field that violates the deployed posture and its expected and
  /// detected values.
  public struct PolicyDriftDetails: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the updated field, for example
    /// constraint.implementation.policy_rules[0].enforce
    public var field: Swift.String = Swift.String()

    /// The value of this field that was configured in a posture, for example,
    /// `true` or `allowed_values={"projects/29831892"}`.
    public var expectedValue: Swift.String = Swift.String()

    /// The detected value that violates the deployed posture, for example,
    /// `false` or `allowed_values={"projects/22831892"}`.
    public var detectedValue: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PolicyDriftDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PolicyDriftDetails().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let field = CodingKeys(stringValue: "field")
      static let expectedValue = CodingKeys(stringValue: "expectedValue")
      static let detectedValue = CodingKeys(stringValue: "detectedValue")

      static let _knownKeys: Set<Swift.String> = [
        "field",
        "expectedValue",
        "detectedValue",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .field) {
        self.field = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .expectedValue) {
        self.expectedValue = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .detectedValue) {
        self.detectedValue = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.field, forKey: .field)
      try container.encode(self.expectedValue, forKey: .expectedValue)
      try container.encode(self.detectedValue, forKey: .detectedValue)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.SecurityPosture.PolicyDriftDetails"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.SecurityPosture"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
