// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class SecurityCenterLogging: SecurityCenterStub {
    let inner: any SecurityCenterStub
    let logger: Logger

    public init(_ inner: any SecurityCenterStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-securitycenter-v2"
      logger[metadataKey: "gcp.client.service"] = "securitycenter"
      logger[metadataKey: "gcp.experimental.swift.client"] = "SecurityCenter"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func batchCreateResourceValueConfigs(
      request: BatchCreateResourceValueConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.BatchCreateResourceValueConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchCreateResourceValueConfigs",
        action: {
          (r: BatchCreateResourceValueConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.BatchCreateResourceValueConfigsResponse
          in
          return try await self.inner.batchCreateResourceValueConfigs(request: r, options: o)
        })
    }

    public func bulkMuteFindings(
      request: BulkMuteFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "bulkMuteFindings",
        action: {
          (r: BulkMuteFindingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.bulkMuteFindings(request: r, options: o)
        })
    }

    public func createBigQueryExport(
      request: CreateBigQueryExportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.BigQueryExport {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBigQueryExport",
        action: {
          (r: CreateBigQueryExportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.BigQueryExport
          in
          return try await self.inner.createBigQueryExport(request: r, options: o)
        })
    }

    public func createFinding(
      request: CreateFindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.Finding {
      try await self._intercept(
        request: request,
        options: options,
        name: "createFinding",
        action: {
          (r: CreateFindingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.Finding
          in
          return try await self.inner.createFinding(request: r, options: o)
        })
    }

    public func createMuteConfig(
      request: CreateMuteConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.MuteConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createMuteConfig",
        action: {
          (r: CreateMuteConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.MuteConfig
          in
          return try await self.inner.createMuteConfig(request: r, options: o)
        })
    }

    public func createNotificationConfig(
      request: CreateNotificationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.NotificationConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createNotificationConfig",
        action: {
          (r: CreateNotificationConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.NotificationConfig
          in
          return try await self.inner.createNotificationConfig(request: r, options: o)
        })
    }

    public func createSource(
      request: CreateSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.Source {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSource",
        action: {
          (r: CreateSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.Source
          in
          return try await self.inner.createSource(request: r, options: o)
        })
    }

    public func deleteBigQueryExport(
      request: DeleteBigQueryExportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBigQueryExport",
        action: {
          (r: DeleteBigQueryExportRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteBigQueryExport(request: r, options: o)
        })
    }

    public func deleteMuteConfig(
      request: DeleteMuteConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteMuteConfig",
        action: {
          (r: DeleteMuteConfigRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteMuteConfig(request: r, options: o)
        })
    }

    public func deleteNotificationConfig(
      request: DeleteNotificationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteNotificationConfig",
        action: {
          (r: DeleteNotificationConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteNotificationConfig(request: r, options: o)
        })
    }

    public func deleteResourceValueConfig(
      request: DeleteResourceValueConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteResourceValueConfig",
        action: {
          (r: DeleteResourceValueConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteResourceValueConfig(request: r, options: o)
        })
    }

    public func getBigQueryExport(
      request: GetBigQueryExportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.BigQueryExport {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBigQueryExport",
        action: {
          (r: GetBigQueryExportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.BigQueryExport
          in
          return try await self.inner.getBigQueryExport(request: r, options: o)
        })
    }

    public func getSimulation(
      request: GetSimulationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.Simulation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSimulation",
        action: {
          (r: GetSimulationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.Simulation
          in
          return try await self.inner.getSimulation(request: r, options: o)
        })
    }

    public func getValuedResource(
      request: GetValuedResourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ValuedResource {
      try await self._intercept(
        request: request,
        options: options,
        name: "getValuedResource",
        action: {
          (r: GetValuedResourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ValuedResource
          in
          return try await self.inner.getValuedResource(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func getMuteConfig(
      request: GetMuteConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.MuteConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMuteConfig",
        action: {
          (r: GetMuteConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.MuteConfig
          in
          return try await self.inner.getMuteConfig(request: r, options: o)
        })
    }

    public func getNotificationConfig(
      request: GetNotificationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.NotificationConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNotificationConfig",
        action: {
          (r: GetNotificationConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.NotificationConfig
          in
          return try await self.inner.getNotificationConfig(request: r, options: o)
        })
    }

    public func getResourceValueConfig(
      request: GetResourceValueConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ResourceValueConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getResourceValueConfig",
        action: {
          (r: GetResourceValueConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ResourceValueConfig
          in
          return try await self.inner.getResourceValueConfig(request: r, options: o)
        })
    }

    public func getSource(
      request: GetSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.Source {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSource",
        action: {
          (r: GetSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.Source
          in
          return try await self.inner.getSource(request: r, options: o)
        })
    }

    public func groupFindings(
      request: GroupFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.GroupFindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "groupFindings",
        action: {
          (r: GroupFindingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.GroupFindingsResponse
          in
          return try await self.inner.groupFindings(request: r, options: o)
        })
    }

    public func listAttackPaths(
      request: ListAttackPathsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ListAttackPathsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAttackPaths",
        action: {
          (r: ListAttackPathsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ListAttackPathsResponse
          in
          return try await self.inner.listAttackPaths(request: r, options: o)
        })
    }

    public func listBigQueryExports(
      request: ListBigQueryExportsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ListBigQueryExportsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBigQueryExports",
        action: {
          (r: ListBigQueryExportsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ListBigQueryExportsResponse
          in
          return try await self.inner.listBigQueryExports(request: r, options: o)
        })
    }

    public func listFindings(
      request: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ListFindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFindings",
        action: {
          (r: ListFindingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ListFindingsResponse
          in
          return try await self.inner.listFindings(request: r, options: o)
        })
    }

    public func listMuteConfigs(
      request: ListMuteConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ListMuteConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMuteConfigs",
        action: {
          (r: ListMuteConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ListMuteConfigsResponse
          in
          return try await self.inner.listMuteConfigs(request: r, options: o)
        })
    }

    public func listNotificationConfigs(
      request: ListNotificationConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ListNotificationConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNotificationConfigs",
        action: {
          (r: ListNotificationConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ListNotificationConfigsResponse
          in
          return try await self.inner.listNotificationConfigs(request: r, options: o)
        })
    }

    public func listResourceValueConfigs(
      request: ListResourceValueConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ListResourceValueConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listResourceValueConfigs",
        action: {
          (r: ListResourceValueConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ListResourceValueConfigsResponse
          in
          return try await self.inner.listResourceValueConfigs(request: r, options: o)
        })
    }

    public func listSources(
      request: ListSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ListSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSources",
        action: {
          (r: ListSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ListSourcesResponse
          in
          return try await self.inner.listSources(request: r, options: o)
        })
    }

    public func listValuedResources(
      request: ListValuedResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ListValuedResourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listValuedResources",
        action: {
          (r: ListValuedResourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ListValuedResourcesResponse
          in
          return try await self.inner.listValuedResources(request: r, options: o)
        })
    }

    public func setFindingState(
      request: SetFindingStateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.Finding {
      try await self._intercept(
        request: request,
        options: options,
        name: "setFindingState",
        action: {
          (r: SetFindingStateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.Finding
          in
          return try await self.inner.setFindingState(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func setMute(
      request: SetMuteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.Finding {
      try await self._intercept(
        request: request,
        options: options,
        name: "setMute",
        action: {
          (r: SetMuteRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.Finding
          in
          return try await self.inner.setMute(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func updateBigQueryExport(
      request: UpdateBigQueryExportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.BigQueryExport {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBigQueryExport",
        action: {
          (r: UpdateBigQueryExportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.BigQueryExport
          in
          return try await self.inner.updateBigQueryExport(request: r, options: o)
        })
    }

    public func updateExternalSystem(
      request: UpdateExternalSystemRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ExternalSystem {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateExternalSystem",
        action: {
          (r: UpdateExternalSystemRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ExternalSystem
          in
          return try await self.inner.updateExternalSystem(request: r, options: o)
        })
    }

    public func updateFinding(
      request: UpdateFindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.Finding {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateFinding",
        action: {
          (r: UpdateFindingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.Finding
          in
          return try await self.inner.updateFinding(request: r, options: o)
        })
    }

    public func updateMuteConfig(
      request: UpdateMuteConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.MuteConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateMuteConfig",
        action: {
          (r: UpdateMuteConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.MuteConfig
          in
          return try await self.inner.updateMuteConfig(request: r, options: o)
        })
    }

    public func updateNotificationConfig(
      request: UpdateNotificationConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.NotificationConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNotificationConfig",
        action: {
          (r: UpdateNotificationConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.NotificationConfig
          in
          return try await self.inner.updateNotificationConfig(request: r, options: o)
        })
    }

    public func updateResourceValueConfig(
      request: UpdateResourceValueConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.ResourceValueConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateResourceValueConfig",
        action: {
          (r: UpdateResourceValueConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.ResourceValueConfig
          in
          return try await self.inner.updateResourceValueConfig(request: r, options: o)
        })
    }

    public func updateSecurityMarks(
      request: UpdateSecurityMarksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.SecurityMarks {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSecurityMarks",
        action: {
          (r: UpdateSecurityMarksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.SecurityMarks
          in
          return try await self.inner.updateSecurityMarks(request: r, options: o)
        })
    }

    public func updateSource(
      request: UpdateSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterV2.Source {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSource",
        action: {
          (r: UpdateSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterV2.Source
          in
          return try await self.inner.updateSource(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
