// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a posture that is deployed on Google Cloud by the
/// Security Command Center Posture Management service.
/// A posture contains one or more policy sets. A policy set is a
/// group of policies that enforce a set of security rules on Google
/// Cloud.
public struct SecurityPosture: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the posture, for example, `CIS-Posture`.
  public var name: Swift.String = Swift.String()

  /// The version of the posture, for example, `c7cfa2a8`.
  public var revisionId: Swift.String = Swift.String()

  /// The project, folder, or organization on which the posture is deployed,
  /// for example, `projects/{project_number}`.
  public var postureDeploymentResource: Swift.String = Swift.String()

  /// The name of the posture deployment, for example,
  /// `organizations/{org_id}/posturedeployments/{posture_deployment_id}`.
  public var postureDeployment: Swift.String = Swift.String()

  /// The name of the updated policy, for example,
  /// `projects/{project_id}/policies/{constraint_name}`.
  public var changedPolicy: Swift.String = Swift.String()

  /// The name of the updated policy set, for example, `cis-policyset`.
  public var policySet: Swift.String = Swift.String()

  /// The ID of the updated policy, for example, `compute-policy-1`.
  public var policy: Swift.String = Swift.String()

  /// The details about a change in an updated policy that violates the deployed
  /// posture.
  public var policyDriftDetails: [SecurityPosture.PolicyDriftDetails] = []

  /// Initialize a new instance of `SecurityPosture`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecurityPosture().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The policy field that violates the deployed posture and its expected and
  /// detected values.
  public struct PolicyDriftDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The name of the updated field, for example
    /// constraint.implementation.policy_rules[0].enforce
    public var field: Swift.String = Swift.String()

    /// The value of this field that was configured in a posture, for example,
    /// `true` or `allowed_values={"projects/29831892"}`.
    public var expectedValue: Swift.String = Swift.String()

    /// The detected value that violates the deployed posture, for example,
    /// `false` or `allowed_values={"projects/22831892"}`.
    public var detectedValue: Swift.String = Swift.String()

    /// Initialize a new instance of `PolicyDriftDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PolicyDriftDetails().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securitycenter.v2.SecurityPosture.PolicyDriftDetails"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.SecurityPosture"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
