// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for updating a finding's mute status.
public struct SetMuteRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The [relative resource
  /// name](https://cloud.google.com/apis/design/resource_names#relative_resource_name)
  /// of the finding. If no location is specified, finding is assumed to be in
  /// global. The following list shows some examples:
  ///
  /// +
  /// `organizations/{organization_id}/sources/{source_id}/findings/{finding_id}`
  /// +
  /// `organizations/{organization_id}/sources/{source_id}/locations/{location_id}/findings/{finding_id}`
  /// + `folders/{folder_id}/sources/{source_id}/findings/{finding_id}`
  /// +
  /// `folders/{folder_id}/sources/{source_id}/locations/{location_id}/findings/{finding_id}`
  /// + `projects/{project_id}/sources/{source_id}/findings/{finding_id}`
  /// +
  /// `projects/{project_id}/sources/{source_id}/locations/{location_id}/findings/{finding_id}`
  public var name: Swift.String = Swift.String()

  /// Required. The desired state of the Mute.
  public var mute: Finding.Mute = Finding.Mute()

  /// Initialize a new instance of `SetMuteRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SetMuteRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.SetMuteRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
