// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Attack path simulation
public struct Simulation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Full resource name of the Simulation:
  /// `organizations/123/simulations/456`
  public var name: Swift.String = Swift.String()

  /// Output only. Time simulation was created
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Resource value configurations' metadata used in this simulation. Maximum of
  /// 100.
  public var resourceValueConfigsMetadata: [ResourceValueConfigMetadata] = []

  /// Indicates which cloud provider was used in this simulation.
  public var cloudProvider: CloudProvider = CloudProvider()

  /// Initialize a new instance of `Simulation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Simulation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.Simulation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
