// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Contains details about a group of security issues that, when the issues
/// occur together, represent a greater risk than when the issues occur
/// independently. A group of such issues is referred to as a toxic
/// combination.
public struct ToxicCombination: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The
  /// [Attack exposure
  /// score](https://cloud.google.com/security-command-center/docs/attack-exposure-learn#attack_exposure_scores)
  /// of this toxic combination. The score is a measure of how much this toxic
  /// combination exposes one or more high-value resources to potential attack.
  public var attackExposureScore: Swift.Double = Swift.Double()

  /// List of resource names of findings associated with this toxic combination.
  /// For example, `organizations/123/sources/456/findings/789`.
  public var relatedFindings: [Swift.String] = []

  /// Initialize a new instance of `ToxicCombination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ToxicCombination().with { $0.attackExposureScore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.ToxicCombination"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
