// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A resource that is determined to have value to a user's system
public struct ValuedResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Valued resource name, for example,
  ///  e.g.:
  ///  `organizations/123/simulations/456/valuedResources/789`
  public var name: Swift.String = Swift.String()

  /// The
  /// [full resource
  /// name](https://cloud.google.com/apis/design/resource_names#full_resource_name)
  /// of the valued resource.
  public var resource: Swift.String = Swift.String()

  /// The [resource
  /// type](https://cloud.google.com/asset-inventory/docs/supported-asset-types)
  /// of the valued resource.
  public var resourceType: Swift.String = Swift.String()

  /// Human-readable name of the valued resource.
  public var displayName: Swift.String = Swift.String()

  /// How valuable this resource is.
  public var resourceValue: ValuedResource.ResourceValue = ValuedResource.ResourceValue()

  /// Exposed score for this valued resource. A value of 0 means no exposure was
  /// detected exposure.
  public var exposedScore: Swift.Double = Swift.Double()

  /// List of resource value configurations' metadata used to determine the value
  /// of this resource. Maximum of 100.
  public var resourceValueConfigsUsed: [ResourceValueConfigMetadata] = []

  /// Initialize a new instance of `ValuedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValuedResource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// How valuable the resource is.
  public enum ResourceValue: Codable, Equatable, Sendable {
    /// The resource value isn't specified.
    case unspecified
    /// This is a low-value resource.
    case low
    /// This is a medium-value resource.
    case medium
    /// This is a high-value resource.
    case high
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .low: return 1
      case .medium: return 2
      case .high: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESOURCE_VALUE_UNSPECIFIED"
      case .low: return "RESOURCE_VALUE_LOW"
      case .medium: return "RESOURCE_VALUE_MEDIUM"
      case .high: return "RESOURCE_VALUE_HIGH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResourceValue/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESOURCE_VALUE_UNSPECIFIED": self = .unspecified
      case "RESOURCE_VALUE_LOW": self = .low
      case "RESOURCE_VALUE_MEDIUM": self = .medium
      case "RESOURCE_VALUE_HIGH": self = .high
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResourceValue/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .low
      case 2: self = .medium
      case 3: self = .high
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .low: return try container.encode(1)
      case .medium: return try container.encode(2)
      case .high: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.ValuedResource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
