// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A resource that is determined to have value to a user's system
public struct ValuedResource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Valued resource name, for example,
  ///  e.g.:
  ///  `organizations/123/simulations/456/valuedResources/789`
  public var name: Swift.String = Swift.String()

  /// The
  /// [full resource
  /// name](https://cloud.google.com/apis/design/resource_names#full_resource_name)
  /// of the valued resource.
  public var resource: Swift.String = Swift.String()

  /// The [resource
  /// type](https://cloud.google.com/asset-inventory/docs/supported-asset-types)
  /// of the valued resource.
  public var resourceType: Swift.String = Swift.String()

  /// Human-readable name of the valued resource.
  public var displayName: Swift.String = Swift.String()

  /// How valuable this resource is.
  public var resourceValue: ValuedResource.ResourceValue = ValuedResource.ResourceValue()

  /// Exposed score for this valued resource. A value of 0 means no exposure was
  /// detected exposure.
  public var exposedScore: Swift.Double = Swift.Double()

  /// List of resource value configurations' metadata used to determine the value
  /// of this resource. Maximum of 100.
  public var resourceValueConfigsUsed: [ResourceValueConfigMetadata] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ValuedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValuedResource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let resource = CodingKeys(stringValue: "resource")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let resourceValue = CodingKeys(stringValue: "resourceValue")
    static let exposedScore = CodingKeys(stringValue: "exposedScore")
    static let resourceValueConfigsUsed = CodingKeys(stringValue: "resourceValueConfigsUsed")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "resource",
      "resourceType",
      "displayName",
      "resourceValue",
      "exposedScore",
      "resourceValueConfigsUsed",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
      self.resource = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(
      ValuedResource.ResourceValue.self, forKey: .resourceValue)
    {
      self.resourceValue = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .exposedScore) {
      self.exposedScore = value
    }
    if let value = try container.decodeIfPresent(
      [ResourceValueConfigMetadata].self, forKey: .resourceValueConfigsUsed)
    {
      self.resourceValueConfigsUsed = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.resource, forKey: .resource)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.resourceValue, forKey: .resourceValue)
    try container.encode(self.exposedScore, forKey: .exposedScore)
    try container.encode(self.resourceValueConfigsUsed, forKey: .resourceValueConfigsUsed)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// How valuable the resource is.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ResourceValue: Codable, Equatable, Hashable, Sendable {
    /// The resource value isn't specified.
    case unspecified
    /// This is a low-value resource.
    case low
    /// This is a medium-value resource.
    case medium
    /// This is a high-value resource.
    case high
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .low: return 1
      case .medium: return 2
      case .high: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESOURCE_VALUE_UNSPECIFIED"
      case .low: return "RESOURCE_VALUE_LOW"
      case .medium: return "RESOURCE_VALUE_MEDIUM"
      case .high: return "RESOURCE_VALUE_HIGH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResourceValue/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESOURCE_VALUE_UNSPECIFIED": self = .unspecified
      case "RESOURCE_VALUE_LOW": self = .low
      case "RESOURCE_VALUE_MEDIUM": self = .medium
      case "RESOURCE_VALUE_HIGH": self = .high
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResourceValue/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .low
      case 2: self = .medium
      case 3: self = .high
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RESOURCE_VALUE_UNSPECIFIED")
      case .low: return try container.encode("RESOURCE_VALUE_LOW")
      case .medium: return try container.encode("RESOURCE_VALUE_MEDIUM")
      case .high: return try container.encode("RESOURCE_VALUE_HIGH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycenter.v2.ValuedResource"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
